language: node_js

node_js: 8

jobs:  
  include:
    - stage: test
      before_install: yarn global add greenkeeper-lockfile@1
      before_install: yarn global add greenkeeper-lockfile@1
      script: yarn test:ci
      after_script: greenkeeper-lockfile-upload
      after_success: yarn codecov
    - stage: deploy
      if: branch = master
      script: yarn release